# Generated by Django 4.2.7 on 2023-11-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingtracks',
            name='duration',
        ),
    ]
