# Generated by Django 4.2.7 on 2023-11-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0002_remove_trendingtracks_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingtracks',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
