# Generated by Django 4.2.7 on 2023-11-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0005_alter_trendingtracks_artist_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtracks',
            name='mood',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
